name: aquaponics
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  equatable: ^2.0.7
  go_router: ^14.8.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
