// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_5rnFEbF6aR7j0p13IftYaDWKhplA5E',
    appId: '1:709758517780:web:d0dcad11909ff3de991d01',
    messagingSenderId: '709758517780',
    projectId: 'aquaponics-46127',
    authDomain: 'aquaponics-46127.firebaseapp.com',
    storageBucket: 'aquaponics-46127.firebasestorage.app',
    measurementId: 'G-QP3D5SN051',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlw20VWsM8oCjfpC46-uDYjaR2QP-mDhM',
    appId: '1:709758517780:android:18faf8ea742b34e1991d01',
    messagingSenderId: '709758517780',
    projectId: 'aquaponics-46127',
    storageBucket: 'aquaponics-46127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCHa1Lht6elF9M6qRGEtY7vNBoTsatevQ',
    appId: '1:709758517780:ios:08bd977eaa193bfd991d01',
    messagingSenderId: '709758517780',
    projectId: 'aquaponics-46127',
    storageBucket: 'aquaponics-46127.firebasestorage.app',
    iosBundleId: 'com.example.aquaponics',
  );
}
